bboard/urls.py
from django.urls import path

from bboard.views import index, by_rubric, BbCreateView

app_name = 'bboard'

urlpatterns = [
    path('add/', BbCreateView.as_view(), name='bb_add'),
    path('<int:rubric_id>', by_rubric, name='by_rubric'),
    path('', index, name='index'),
]

samplesite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bboard.urls', namespace='board')),

    path('admin/', admin.site.urls),
]

bboard/models.py
from django.db import models


class Rubric(models.Model):
    name = models.CharField(
        max_length=20,
        db_index=True,
        verbose_name="Название",
    )

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = 'Рубрика'
        verbose_name_plural = 'Рубрики'
        ordering = ['name']


class Bb(models.Model):
    title = models.CharField(
        max_length=50,
        verbose_name='Товар',
    )

    content = models.TextField(
        null=True,
        blank=True,
        verbose_name='Описание',
    )

    price = models.DecimalField(
        null=True,
        blank=True,
        max_digits=13,
        decimal_places=2,
        verbose_name='Цена',
    )

    published = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name='Опубликовано',
    )

    rubric = models.ForeignKey(
        'Rubric',
        null=True,
        on_delete=models.PROTECT,
        verbose_name='Рубрика'
    )

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'
        ordering = ['-published']

bboard/forms.py
from django.forms import ModelForm

from bboard.models import Bb

class BbForm(ModelForm):
    class Meta:
        model = Bb
        fields = ('title', 'content', 'price', 'rubric')

bboard/views.py
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.shortcuts import render
from django.template import loader
from django.views.generic import CreateView

from bboard.forms import BbForm
from bboard.models import Bb, Rubric


# def index(request):
#     s = 'Список объявлений\r\n\r\n\r\n'
#
#     for bb in Bb.objects.order_by('-published'):
#         s += bb.title + '\r\n' + bb.content + '\r\n\r\n'
#
#     return HttpResponse(s, content_type='text/plain; charset=utf-8')


# def index(request):
#     template = loader.get_template('index.html')
#     bbs = Bb.objects.order_by('-published')
#     context = {'bbs': bbs}
#
#     return HttpResponse(template.render(context, request))


def index(request):
    bbs = Bb.objects.order_by('-published')
    rubrics = Rubric.objects.all()
    context = {'bbs': bbs, 'rubrics': rubrics}

    return render(request, 'index.html', context)

def by_rubric(request, rubric_id):
    bbs = Bb.objects.filter(rubric=rubric_id)
    rubrics = Rubric.objects.all()
    current_rubric = Rubric.objects.get(id=rubric_id)
    context = {'bbs': bbs, 'rubrics': rubrics, 'current_rubric': current_rubric}

    return render(request, 'by_rubric.html', context)


class BbCreateView(CreateView):
    template_name = 'create.html'
    form_class = BbForm
    success_url = reverse_lazy('bboard:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rubrics'] = Rubric.objects.all()


        return context

templates/by_rubric.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{current_rubric.name}}: Доска объявлений</title>
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Объявления</h1>
    <h2>Рубрика: {{current_rubric.name}}</h2>

    <div>
        <a href="/">Главная</a>
        <a href="/">Добавить</a>
        {% for rubric in rubrics %}
            <a href="/{{rubric.id}}/">{{ rubric.name }}</a>
        {% endfor %}
    </div>
    {% for bb in bbs %}
        <div>
            <h2>{{ bb.title }}</h2>
            <p>{{ bb.content }}</p>
            <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
        </div>
    {% endfor %}
</body>
</html>

templates/create.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Главная :: Доска объявлений</title>
</head>
<body>

    <h1>Объявления</h1>

        <div>
        <a href="{% url 'bboard:index' %}">Главная</a>
        {% for rubric in rubrics %}
            <a href="{% url 'bboard:by_rubric' rubric.pk %}">{{rubric.name}}</a>
        {% endfor %}
    </div>

    {% for bb in bbs %}
        <div>
            <h2>{{ bb.title }}</h2>
            <p>{{ bb.content }}</p>
            <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
        </div>
    {% endfor %}


    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Главная :: Доска объявлений</title>
</head>
<body>

    <h1>Объявления</h1>

    {% for bb in bbs %}
        <div>
            <h2>{{ bb.title }}</h2>
            <p>{{ bb.content }}</p>
            <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
        </div>
    {% endfor %}

</body>
</html>